### ISSUE TITLE
Bugs: hide-and-seek

### ISSUE THREAD

**Issue by cynthiainga** [jerryowusu/personal-portfolio#22]
Hey Jerry!

So I checked your project and I tried to check if in your project there were no bugs and by surprise, I found some bugs but it's not a big problem it can be fixed
So there are some bugs that I found:

- All your `.js` files are not found in the `.html` file, it's not a big deal you need just to add something. For example in your `.html.` file you write `<script src="/js/main.js"></script>` so to locate the `main.js` file in your `js` folder you just need to add a dot  `.` before `/js`. Instead `<script src="/js/main.js"></script>` it will be that `<script src="./js/main.js"></script>` and you need to do this change on the line `144, 145, 146` and your files will be found.

- And in your `project.js` file all your images are not found, it is just a problem of notation.
 Instead `'../images/project1-snapshot.svg' `  it will be that ` './images/project1-snapshot.svg' ` and all your images are appear. To locate the image in the folder you don't need two dots `..` except if you use `" "` but if you use ` ' ' ` you need only one dot `.`. 
And to add one last thing in your `style.css` file at line `180` you forgot to put your URL image in `" "`.

 **Feel free to leave any questions or comments thread if something is not 100% clear.**
### Thanks and happy coding :blush:

**Comment by jerryowusu** [comment]
Resolved. Thanks
